- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  roles:
    - homebrew
    - homebrew-cask
    - oh-my-zsh
    - ricty
  vars:
    # Tap external Homebrew repositories.
    #
    # e.g.
    # - homebrew/binary
    homebrew_repositories:

    # Managed Homebrew packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state, install_options: [with-baz, enable-debug] }
    #
    # state choices: [head, latest, present, absent, linked, unlinked] (default: latest)
    # install_options: string or sequence (default: none)
    homebrew_packages:
      - readline
      - openssl
      - { name: openssl, state: linked, install_options: force }
      - git
      - heroku-toolbelt
      - peco
      - rbenv
      - ruby-build
      - the_silver_searcher
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - wget
      - tmux
      - phantomjs
      - reattach-to-user-namespace

    # Tap external Homebrew Cask repositories.
    homebrew_cask_repositories:
      - caskroom/versions
      - sanemat/font # for ricty
    # Managed Homebrew Cask packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state }
    #
    # state choices: [present, absent, installed, uninstalled] (default: present)
    homebrew_cask_packages:
      - firefox-ja
      - google-chrome
      - google-japanese-ime
      - iterm2
      - java6
      - karabiner
      - rubymine
      - slack
      - sublime-text3
      - macvim-kaoriya
      - appcleaner
      - bettertouchtool
      - xtrafinder
      - skitch
      - rubymine
      - webstorm
      - dash
      - flashlight
      - hyperswitch
      - licecap
